version: '2.4'
services:

  server:
    ports:
    - 6443:6443

  agent:
    ports:
    - 80:80
    - 443:443
    mem_limit: 8589934592
    memswap_limit: 0

  sut:
    environment:
    - KEEP_RUNNING=true

volumes:
  admin:
    driver: local
    driver_opts:
      type: none
      device: $PWD/test
      o: bind
