version: '2.4'
services:

  server:
    image: rancher/k3s:v1.17.5-k3s1@sha256:3025ecfa3c7c3a262a97435cb7c9c182d22b93d014bac767019d65bdce586786
    command:
    - server
    - --disable-agent
    - --node-name=server
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_TOKEN=somethingtotallyrandom
    - K3S_KUBECONFIG_OUTPUT=/admin/.kube/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    expose:
    - 6443
    - 8472
    - 10250
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    - admin:/admin
    mem_limit:  300000000
    memswap_limit: 0

  agent:
    depends_on:
    - server
    image: rancher/k3s:v1.17.5-k3s1@sha256:3025ecfa3c7c3a262a97435cb7c9c182d22b93d014bac767019d65bdce586786
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=somethingtotallyrandom
    expose:
    - 8472
    - 10250
    mem_limit: 1500000000
    memswap_limit: 0

  sut:
    depends_on:
    - server
    image: solsson/ystack-runner@sha256:95aff82cb5245e93c8f3193253b054a5628f6421ddc5f93b5dfff0cf38d1bbc7
    environment:
    - PROMETHEUS_OPERATOR_BASE=github.com/coreos/prometheus-operator/?ref=9877ec897fc7ea4f50d947ca824ae0c30c185105
    - KUBECONFIG_WAIT=30
    - KEEP_RUNNING=false
    volumes:
    - admin:/admin
    entrypoint:
    - /bin/bash
    - -cx
    command:
    - |
      tail -f /dev/null
      mkdir ~/.kube
      until test -f /admin/.kube/kubeconfig.yaml; do
        [ $$KUBECONFIG_WAIT -gt 0 ] || exit ${BULID_EXIT_CODE_ON_NO_CLUSTER:-0}
        KUBECONFIG_WAIT=$$(( $$KUBECONFIG_WAIT - 1 ))
        echo "Waiting for a kubeconfig ..." && sleep 1
      done
      set -e
      cat /admin/.kube/kubeconfig.yaml | sed 's|127.0.0.1|server|' > ~/.kube/config
      kubectl-waitretry --for=condition=Ready node --all
      kubectl get namespace monitoring 2>/dev/null || kubectl create namespace monitoring
      kubectl apply -k $$PROMETHEUS_OPERATOR_BASE
      if [ "$$KEEP_RUNNING" = "true" ]; then
        echo "Will stay running for manual work"
        sleep infinity
      fi
    mem_limit:   80000000
    memswap_limit: 0

volumes:
  k3s-server: {}
  admin: {}
