version: '2.4'
services:

  kubernetes-mixin:
    build: ./kubernetes-mixin
    environment:
    - DEBUG=true
    entrypoint:
    - sh
    - -ce
    command:
    - |
      cat << EOF > /kustomize-base/rules.yaml
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        name: kubernetes-mixin-rules
      spec:
      EOF
      cat prometheus_rules.yaml | sed 's|^|  |' >> /kustomize-base/rules.yaml

      cat << EOF > /kustomize-base/alerts.yaml
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        name: kubernetes-mixin-alerts
      spec:
      EOF
      cat prometheus_alerts.yaml | sed 's|^|  |' \
        | sed 's|{job="kube-apiserver"}|{job="apiserver"}|' \
        >> /kustomize-base/alerts.yaml

      cp -rv dashboards_out/* /dashboards-kustomize-base
      cat << EOF > /dashboards-kustomize-base/kustomization.yaml
      # It should be possible to extend this set of dashboards using the "replace" behavior
      # Meant to be used with kubectl create -k and kubectl replace -k
      # (unless we learn how to get rid of last-applied-configuration with apply)
      generatorOptions:
        disableNameSuffixHash: true
      configMapGenerator:
      - name: kubernets-mixin-grafana-dashboards
        files:
      EOF
      find dashboards_out -name \*.json | sed 's|dashboards_out/\(.*\)|  - \1=\1|' >> /dashboards-kustomize-base/kustomization.yaml
    volumes:
    - ./kubernetes-mixin:/kustomize-base
    - ./kubernetes-mixin-dashboards:/dashboards-kustomize-base

  sut:
    image: golang:1.14.3-buster@sha256:6edcc1af51905a860d510a7d4bb0a83d9a0e381cf05c07f23722020a4c688e6f
    #environment:
    #- DEBUG=true
    entrypoint:
    - bash
    - -ce
    command:
    - |
      echo "No tests"
