kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-rules
  namespace: monitoring
  annotations:
    prometheus.io/rules: "true"
data:
  ContainerScrapeError.txt: |-
    ALERT ContainerScrapeError
    IF container_scrape_error > 0
    FOR 1m
    LABELS { severity = "warning" }
    ANNOTATIONS {
      description = "Container Scrape Error ({{ $value }})."
    }
  DeploymentRetries.txt: |-
    ALERT TooManyDeploymentRetries
    IF deployment_retries > 3
    FOR 1m
    LABELS { severity = "critical" }
    ANNOTATIONS {
      description = "Deployment retries: ({{ $value }})."
    }
