apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/Yolean/kubernetes-assert/runtime-nodejs/kustomize?ref=f015a4f1f6408dddef80cdba9b734664c275b570
namePrefix: example-project-
commonLabels:
  app: example-project
images:
- name: yolean/assert-runtime-nodejs
  newName: builds-registry.ystack.svc.cluster.local/yolean/kubernetes-assert/example-project
  newTag: null
