apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: assertions-runtime-nodejs
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local/yolean/kubernetes-assert-runtime-nodejs
    context: ./
    custom:
      buildCommand: y-build
      dependencies:
        dockerfile:
          path: Dockerfile
    sync:
      manual:
      # intentionally differs from the COPY source, so we test addition of spec files after start
      - src: 'src/**'
        dest: .
deploy:
  kustomize: {}
