apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: custom
  namespace: monitoring
  labels:
    prometheus: custom
spec:
  replicas: 1
  version: v2.2.1
  serviceAccountName: prometheus-custom
  serviceMonitorSelector:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: custom
      role: alert-rules
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus
      spec:
        resources:
          requests:
            storage: 100Gi
