---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-custom
  namespace: monitoring
  annotations:
    manifest-origin: github.com/Yolean/kubernetes-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: monitoring-by-prometheus-annotations
  annotations:
    manifest-origin: github.com/Yolean/kubernetes-monitoring
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups: ["extensions"]
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: monitoring-by-prometheus-annotations
  annotations:
    manifest-origin: github.com/Yolean/kubernetes-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-by-prometheus-annotations
subjects:
- kind: ServiceAccount
  name: prometheus-custom
  namespace: monitoring
