# `skaffold dev` then add or edit specs under ./src
# `kubectl exec $(kubectl get pods -l sut=runtime -o name) -c runtime -- curl -s http://localhost:9090/metrics`
apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: assert-runtime-nodejs
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local/yolean/kubernetes-assert-runtime-nodejs
    context: ./
    custom:
      buildCommand: y-build
      dependencies:
        dockerfile:
          path: Dockerfile
    sync:
      manual:
      # intentionally differs from the COPY source, so we test addition of spec files after start
      - src: 'src/**'
        dest: .
test:
- image: builds-registry.ystack.svc.cluster.local/yolean/kubernetes-assert-runtime-nodejs
  structureTests:
  - './structure-test/*'
deploy:
  kustomize:
    paths:
    - dev-ystack
