# good for direct access using
#minikube service --namespace=monitoring expose-grafana
#minikube service --namespace=monitoring expose-prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: expose-grafana
  namespace: monitoring
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30030
  selector:
    app: grafana
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: expose-prometheus
  namespace: monitoring
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30090
  selector:
    app: prometheus
  type: NodePort
