apiVersion: 1
datasources:
- name: Prometheus now
  type: prometheus
  #access: proxy
  url: http://prometheus-now:9090
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  jsonData:
    timeInterval: "30s"
- name: Loki
  type: loki
  url: http://loki:3100
