apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

images:
- name: grafana/grafana
  newName: docker.io/grafana/grafana
  newTag: 8.2.3-ubuntu@sha256:c88d397bceca59a1d84528b061ad695c5bc4f77a74e95072889ba33ad0314f46
- name: grafana/grafana-image-renderer
  newName: docker.io/grafana/grafana-image-renderer
  newTag: 3.2.1@sha256:e527d0e29f76537655d395739e700c080270add386ff3bc9b68031bf03e4ff81

resources:
- grafana-service.yaml
- grafana-deployment.yaml

configMapGenerator:
- name: grafana-provisioning-datasources
  files:
  - prometheus-now.yaml=datasources-prometheus-now.yaml
  - loki.yaml=datasources-loki.yaml
- name: grafana-provisioning-dashboards
  files:
  - kubernetes-mixin.yaml=dashboards-kubernetes-mixin.yaml
  - imported.yaml=dashboards-imported.yaml
