apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- grafana-service.yaml
- grafana-deployment.yaml
configMapGenerator:
- name: grafana
  files:
  - datasources.yaml=config-datasources.yaml
  - dashboards.yaml=config-dashboards.yaml
