apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      kubernetes-assert: metrics
  template:
    metadata:
      labels:
        kubernetes-assert: metrics
    spec:
      serviceAccountName: assert
      containers:
      - name: runtime
        # We can't have a tag here because https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#images won't unset it, and Skaffold required no-tag URLs for build
        image: yolean/assert-runtime-nodejs
        env:
        - name: POD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: ASSERT_IS_DEV
          valueFrom:
            fieldRef:
              # This will be true for run --tail as well but that's also a dev-loop use case
              fieldPath: metadata.labels['skaffold.dev/tail']
        ports:
        - containerPort: 9090
          name: prometheus
      # TODO how to do composition at runtime, in Kubernetes, on a file system level?
      # We need to keep the spec builds small, and rely on sync
      # We must support both skaffold run (no file sync) and skaffold dev (with file sync)
