apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      kubernetes-assert: counter
  template:
    metadata:
      labels:
        kubernetes-assert: counter
    spec:
      containers:
      - name: runtime
        # We can't have a tag here because https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#images won't unset it, and Skaffold required no-tag URLs for build
        image: yolean/assert-runtime-nodejs
        ports:
        - containerPort: 9090
          name: prometheus
        #command:
        #- bash
        #- -cex
        #- echo "TEMP sleep" && sleep infinity
      # TODO how to do composition at runtime, in Kubernetes, on a file system level?
      # We need to keep the spec builds small, and rely on sync
      # We must support both skaffold run (no file sync) and skaffold dev (with file sync)
