apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
# the above is from contrib, below is added
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["get", "list", "watch"]
