apiVersion: batch/v1
kind: Job
metadata:
  name: monitoring-installer
spec:
  template:
    metadata:
      name: monitoring-installer
    spec:
      containers:
      - name: kubectl
        # any image with kubectl really
        image: solsson/kafka-initutils@sha256:c266e4836d47c4913b7c25e4409c2a33905bdfdc2007daaf74f7eb98a5e4acb4
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_REPO
          value: coreos/prometheus-operator
        - name: OPERATOR_VERSION
          value: v0.14.0
        - name: OPERATOR_KUBE_DIR
          value: contrib/kube-prometheus/
        - name: DEPLOY_BIN
          value: ./hack/cluster-monitoring/deploy
        workDir: /opt
        command:
        - /bin/bash
        - -cex
        - |-
          curl -SLs -o prometheus-operator.tgz https://github.com/$OPERATOR_REPO/archive/$OPERATOR_VERSION.tar.gz
          tar -xzf prometheus-operator.tgz --strip-components=1 -C ./prometheus-operator
          cd ./prometheus-operator/$OPERATOR_KUBE_DIR

          KUBE_CONTEXT=$(kubectl config view | grep current-context | awk '{print $2}')
          kubectl config set-context $KUBE_CONTEXT --namespace=monitoring

          $DEPLOY_BIN

          echo "Installer finished. You can delete this job."
          tail -f /dev/null
      restartPolicy: Never
      #backoffLimit: 4