apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../runtime-nodejs/kustomize
namePrefix: assert-specs-
commonLabels:
  app: assert-specs
images:
- name: yolean/assert-runtime-nodejs
  newName: builds-registry.ystack.svc.cluster.local:80/yolean/assert-specs
  newTag: null
