apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: assert-specs
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local:80/yolean/assert-specs
    sync:
      manual:
      - src: '**'
        dest: /usr/src/specs
    kaniko:
      reproducible: true
  cluster: {}
deploy:
  kustomize: {}
