apiVersion: apps/v1
kind: Deployment
metadata:
  name: assert-loadtest
  labels:
    app: assert-loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assert-loadtest
  template:
    metadata:
      labels:
        app: assert-loadtest
    spec:
      containers:
      - name: resources
        image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5@sha256:284fcd047cdec35e1b212919bd878ba5ef72f1da12f49ddc199d219fa8b64f4a
        args:
        - --port
        -   "8081"
        ports:
        - name: resources
          containerPort: 8081
      - name: statusrandom
        image: solsson/httpstatus-random
        command: ["/webserver"] # TODO remove after next build
        args:
        - --port
        -   "8082"
        ports:
        - name: statusrandom
          containerPort: 8082
      - name: merge
        image: envoyproxy/envoy:v1.15.0@sha256:f455fd7b45c2fe5d2862e19a3858284bbffc9c72359e0012641b59859d5c68db
        ports:
        - containerPort: 8080
        command:
        - /usr/local/bin/envoy
        - -l
        -   info
        - --config-yaml
        - |
          admin:
            access_log_path: /dev/null
            address:
              socket_address:
                protocol: TCP
                address: 0.0.0.0
                port_value: 9901
          static_resources:
            listeners:
            - name: listener_0
              address:
                socket_address:
                  protocol: TCP
                  address: 0.0.0.0
                  port_value: 8080
              filter_chains:
              - filters:
                - name: envoy.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                    stat_prefix: assert_loadtest
                    access_log:
                    - name: envoy.access_loggers.file
                      filter:
                        not_health_check_filter:  {}
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                        path: /dev/stdout
                    route_config:
                      name: resources
                      virtual_hosts:
                      - name: combined
                        domains: ["*"]
                        routes:
                        - match:
                            prefix: "/statusrandom"
                          route:
                            cluster: statusrandom
                            timeout: 30s
                        - match:
                            prefix: "/ConsumeCPU"
                          route:
                            cluster: resources
                            timeout: 30s
                        - match:
                            prefix: "/ConsumeMem"
                          route:
                            cluster: resources
                            timeout: 30s
                        - match:
                            prefix: "/BumpMetric"
                          route:
                            cluster: resources
                        - match:
                            prefix: "/statusrandom"
                          route:
                            cluster: statusrandom
                        - match:
                            prefix: "/"
                          direct_response:
                            status: 200
                            body:
                              inline_string: |
                                - To consume CPU, POST to /ConsumeCPU
                                - To consume memory, POST to /ConsumeMem
                                - To get random HTTP status, use /statusrandom
                          response_headers_to_add:
                          - header:
                              key: content-type
                              value: text/plain
                          - header:
                              key: cache-control
                              value: max-age=0, no-cache
                    http_filters:
                    - name: envoy.router
            clusters:
            - name: resources
              type: STATIC
              connect_timeout: 0.25s
              load_assignment:
                cluster_name: resources
                endpoints:
                - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          protocol: TCP
                          port_value: 8081
                          address: 127.0.0.1
            - name: statusrandom
              type: STATIC
              connect_timeout: 0.25s
              load_assignment:
                cluster_name: statusrandom
                endpoints:
                - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          protocol: TCP
                          port_value: 8082
                          address: 127.0.0.1
