apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: now
spec:
  replicas: 1
  retention: 2h
  serviceAccountName: prometheus
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
  serviceMonitorSelector:
    matchLabels:
      prometheus: now
  podMonitorSelector:
    matchLabels:
      prometheus: now
  ruleSelector:
    matchLabels:
      prometheus: now
