apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: now
spec:
  replicas: 1
  retention: 2h
  serviceAccountName: prometheus
  image: prom/prometheus:v2.20.1@sha256:788260ebd13613456c168d2eed8290f119f2b6301af2507ff65908d979c66c17
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    # Uncomment on failure to start a new instance. Left out because it may have performance implications, as configmaps may be large.
    #fsGroup: 65534
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
  serviceMonitorNamespaceSelector: {}
  podMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      prometheus: now
  podMonitorSelector:
    matchLabels:
      prometheus: now
  ruleSelector:
    matchLabels:
      prometheus: now
